### ISSUE TITLE
Projector Blueprint Dup bug.

### ISSUE THREAD

**Issue by Arctic-Wolfy** [AdlyTempleton/MineChem#131] opened 2014-02-24 20:38 UTC
I took the blue print out then exited out of the GUI and broke the projector and it dropped itself and another blueprint.

**Comment by AdlyTempleton** [comment] 2014-02-25 01:16
Can't reproduce this.

**Comment by cardenaso11** [comment] 2014-02-25 21:17
I am familiar with this bug, and it only happens when the blueprint is removed via a shift-left click. :D

**Comment by jakimfett** [comment] 2014-05-07 01:07
Closing for now. Need to rework some of the GUI code.

**Closed as completed by jakimfett** 2014-05-07 01:07 UTC
Labels: confirmed bug
