### ISSUE TITLE
(1.6.4) Outbound 250 - MineChem sending out TONS of data.

### ISSUE THREAD

**Issue by Vaygrim** [AdlyTempleton/MineChem#178] opened 2014-05-02 15:47 UTC
![screenshot 2014-05-02 10 32 09](https://cloud.githubusercontent.com/assets/4295188/2864478/9c760818-d210-11e3-9709-625e26a66605.png)

MC 1.6.4
MineChem 5.0.4
YogsCast Complete Mod Pack AND Resonant Rise Mod Pack

As the above picture shows.. the MineChem2 mod is sending out a pretty nasty amount of data packets on a constant basis. Averaging 133 packets per second, 5.736 KiloBytes per second, for a total of 400+ Megabytes since the server was reset last night (roughly 11 hours ago).

Can you please look into this, Jakimfett? I'd greatly appreciate it. Thanks.

**Comment by jakimfett** [comment] 2014-05-07 00:14
After doing a bit of testing, here's the results for each individual machine:

| Machine Name | Inactive | Active |
| --- | --- | --- |
| Microscope | 0kbps | 0kbps |
| Decomposer | 0.938kbps | 1.538kbps |
| Synth Machine | 0.766kbps | 0.781kbps |
| Projector | 0kbps | 0.215kbps |
| Fission | 0kbps | 0kbps |

The projector only hit 0.215kbps for a moment, then it dropped back to 0.

Looks like I need to optimize the Decomposer and Synthesis machines.

**Comment by MFernflower** [comment] 2014-05-24 01:54
I wonder if MaxWolf's rewrite of the netcode would have helped this at all. Can you try with the newest version of MineChem and report back? (On second thought it probably will not help. But it may be worth a shot)

**Comment by jakimfett** [comment] 2014-05-24 02:01
I already tried it. The rewrite didn't fix the data issues, although it may have reduced them somewhat.

**Comment by nanakisan** [comment] 2014-05-24 06:03
Has these results been compared against versions of Minechem before any major refactoring was done? Its been my experience with Minechem that it has always suffered from extreme packet spam.

**Comment by jakimfett** [comment] 2014-05-25 00:52
Yes, I've compared them against previous versions. As I stated above, I need to do an optimization of the Decomposer and Synthesis machines.

**Comment by Maxwolf** [comment] 2014-05-25 02:03
The packet spam is something that will be taken care of soon. I am looking into ways to optimize the machnes to only send data when needed. That is why I did the refactoring and cleanup now it's possible to see exactly what we need to send and when.

All in good time it was definitely something I wanted to address!

**Comment by nanakisan** [comment] 2014-05-25 03:25
Do us all one little favor. When you fix this issue. Fix the server crippling lag caused by the decomposer when players throw chisel marble in that thing.

**Comment by jakimfett** [comment] 2014-05-25 03:29
That was fixed in 5.0.5-Dev5, I highly recommend you download the update @nanakisan. We did strip out ParticlePhysics though, so if you or your players use that portion of the mod, wait until I finish a standalone release for that before updating.

**Comment by nanakisan** [comment] 2014-05-25 03:32
Ahhh i'll check that and see if its in the latest Resonant Rise pack. The last time i checked it was RR 2.8.4.1

**Comment by jakimfett** [comment] 2014-05-25 03:35
Ah, yes...they're waiting on a PP release. Rest assured that the server-crippling lag is fixed in future versions, and I'm working hard on a PP dev release.

**Comment by jakimfett** [comment] 2014-05-30 00:04
This will be fixed in the next dev build (Minechem 5.0.5-Dev6).

The way this was fixed is kinda a patch. Essentially, if a player is more than 20 (it's configurable, but 20 is the default) blocks away from one of the machines, packets aren't sent. Before, every player on the server would get sent a packet every tick.

**Closed as completed** 2014-05-30 00:42 UTC
Labels: confirmed bug
