### ISSUE TITLE
Crash on startup 'registerPotionEffectType'

### ISSUE THREAD

**Issue by lanord** [AdlyTempleton/MineChem#94] opened 2013-10-24 16:46 UTC
Here is the crash report.

http://pastebin.com/QkST9hAh

**Comment by MFernflower** [comment] 2013-10-24 17:10
Could be related to bukkit. Ill check it anyway

**Comment by MFernflower** [comment] 2013-12-12 15:11
I have also sent in a fix for what could have went wrong.

**Comment by jakimfett** [comment] 2014-05-01 03:59
Can't reproduce, closing ticket. If you can reproduce this issue using the latest dev release, please open a new ticket, @lanord

**Closed as completed by jakimfett** 2014-05-01 03:59 UTC
Labels: wontfix
