### ISSUE TITLE
All items can be used to power the fusion reactor

### ISSUE THREAD

**Issue by axelpx** [AdlyTempleton/MineChem#152] opened 2014-04-05 17:26 UTC
As i said, anything can be used instead of the nether star in fusion reactor to combine elements.

Minechem v. 5.0.4

**Comment by jakimfett** [comment] 2014-04-21 18:27
I've confirmed that this is a problem, although in my dev environment it just eats the items, but doesn't power the fusion reactor.

It looks like the GUI isn't verifying that an item is valid fuel before accepting it. I don't have a fix yet, but I'm working on it.

**Comment by jakimfett** [comment] 2014-06-02 05:33
I've refactored the Fusion Reactor code, and made sure that I fixed this in the process. The fix will be in the next dev release.

**Closed as completed by jakimfett** 2014-06-02 05:33 UTC
Labels: confirmed bug, devfix
